# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: boomkrak
description: Senstional bookmark delight from Lieur Co
tagline: Get your resource here
url: boomkrak.github.io

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: app
destination: .tmp

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
author:
  name: Rizqi Nizamil Putra
  email: rizqi@lieur.co
  bio: Web Designer and HTML/CSS Specialist
  twitter: rizqinizamil

# general setting for Jekyll
googleAnalytics: UA-XXXXX-X

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Permalink structure and pagination options
# relative_permalinks: true
permalink: pretty
paginate: 10
paginate_path: 'page:num'
excerpt_separator: '<!--more-->'

# Markdown library
# markdown: redcarpet
# Markdown library options
# redcarpet:
  #extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart', 'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
markdown: kramdown
kramdown:
  input: GFM 
  
highlighter: true

collections:
  tools:
    output: true
    permalink: /:collection/:path/
  tag:
    output: true
    permalink: /:collection/:path/